### ISSUE TITLE
Phase 0 - Clarification question about cloud gaming and the project

### ISSUE THREAD

**Issue by pmwatt** [ICT-Mahidol/2023-ITCS371-2-Michaelsoft-Co.-Ltd.#1]
Hi ajarn @cragkhit  , our group's topic is about Digital Game Distributor. In the video, you mentioned that "user need to download the game when they need to play, and when they finishes everything will be kept on the cloud".

For clarification, may I ask if you are referring to "cloud gaming" (streaming the game when playing, similar to Netflix or xbox cloud gaming) or not?

**Comment by cragkhit** [comment]
Hi @pmwatt. Thanks for asking. To clarify this, actually what I meant is the game must be downloaded first before playing. It will be installed on the user's computer or phone. However, while playing and after finish playing, they can delete the installation and the statuses of the game will be saved to the cloud. This is not a cloud gaming platform where the content is streamed directly in real-time over the internet.

I hope this clarifies your question. Feel free to ask more if you still have any questions.

**Comment by cragkhit** [comment]
Also, good job for creating an issue to ask this question! 👍

**Comment by pmwatt** [comment]
Thank you kub
